name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

concurrency:
  group: example-app-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example-app

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Cache build venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.4
        with:
          version: "latest"
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies with Poetry
        run: |
          poetry install --no-root

  lint:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ./example-app

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install flake8
        run: |
          poetry run poetry add --dev flake8

      - name: Lint with flake8
        run: |
          poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --ignore=F821
          poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  formatter:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ./example-app

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Black
        run: |
          poetry run poetry add --dev black

      - name: Format check with Black
        run: |
          poetry run black --check .

  security:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ./example-app

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Bandit
        run: |
          poetry run poetry add --dev bandit

      - name: Security check with Bandit
        run: |
          poetry run bandit -r .

  unittests:
    runs-on: ubuntu-latest
    needs: [lint, formatter, security]
    defaults:
      run:
        working-directory: ./example-app

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Test with pytest
        run: |
          poetry run pytest
