name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

concurrency:
  group: example-app-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Job 1: Build
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: build-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Cache poetry dependencies
        id: cache-poetry
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.4
        with:
          version: "latest"
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies with Poetry
        run: |
          poetry install --no-root

  # Job 2: Lint
  lint:
    needs: build  # Ensure this runs after 'build'
    runs-on: ubuntu-latest
    concurrency:
      group: lint-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install flake8
        run: |
          poetry add --dev flake8

      - name: Lint with flake8
        run: |
          poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  # Job 3: Formatter (runs after lint)
  formatter:
    needs: lint  # Ensure this runs after 'lint'
    runs-on: ubuntu-latest
    concurrency:
      group: formatter-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install black
        run: |
          poetry add --dev black

      - name: Format with black
        run: |
          poetry run black . --check

  # Job 4: Security (runs after formatter)
  security:
    needs: formatter  # Ensure this runs after 'formatter'
    runs-on: ubuntu-latest
    concurrency:
      group: security-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install safety
        run: |
          poetry add --dev safety

      - name: Run security checks with safety
        run: |
          poetry run safety check

  # Job 5: Unit Tests (runs after build, lint, formatter, and security)
  unit_tests:
    needs: [build, lint, formatter, security]  # Ensure this runs after all the previous jobs
    runs-on: ubuntu-latest
    concurrency:
      group: unittests-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies with Poetry
        run: |
          poetry install --no-root

      - name: Run unit tests with pytest
        run: |
          poetry run pytest
